# GRID
GRID_SIZE= 20
SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
RIGHT_MARGIN = int(SCREEN_WIDTH * 0.2)
TOP_BOTTOM_MARGIN = int(SCREEN_HEIGHT * 0.1)
GRID_PIXEL_SIZE = min(SCREEN_WIDTH - RIGHT_MARGIN, SCREEN_HEIGHT - 2 * TOP_BOTTOM_MARGIN)
CELL_SIZE = GRID_PIXEL_SIZE // GRID_SIZE

# OBSTACLE
PINK = (255, 105, 180)
BLUE = (0, 128, 255)
OBSTACLE_LENGTH = 10
OBSTACLE_SAFETY_MARGIN = 10

# ROBOT ATTRIBUTES
ROBOT_SAFETY_DISTANCE = 10